export const EQUIPMENT_CONFIG = {
    cores: {
        'magnetic': { id: 'magnetic', name: 'Core Magnetico', desc: 'Anelli magnetici rotanti che attirano gemme e XP da +25% distanza.', materials: { 'iron_fragment': 3, 'steel_fragment': 1 }, effect: { type: 'magnet', range: 1.25 }, maxLevel: 1, upgradeCost: null, stage: 1, theme: 'metallico', lootWeight: 1.5 },
        'resistance': { id: 'resistance', name: 'Core di Resistenza', desc: 'Barriera marrone che riduce i danni ricevuti del 5%.', materials: { 'steel_fragment': 3, 'stone_fragment': 2 }, effect: { type: 'resistance', dr: 0.05 }, maxLevel: 1, upgradeCost: null, stage: 1, theme: 'metallico', lootWeight: 1.3 },
        'poison': { id: 'poison', name: 'Core Velenoso', desc: 'Aura verde che avvelena i nemici al contatto infliggendo 3 DPS per 5s.', materials: { 'wood_fragment': 2, 'poison_fragment': 2 }, effect: { type: 'poison', damage: 3, duration: 5000 }, maxLevel: 1, upgradeCost: null, stage: 2, theme: 'organico', lootWeight: 1.2 },
        'shadow': { id: 'shadow', name: "Core d'Ombra", desc: 'Ombra che aumenta la velocità di movimento del 12%.', materials: { 'vine_fragment': 2, 'shadow_fragment': 1 }, effect: { type: 'shadow', speed: 0.12, stealth: 0.3 }, maxLevel: 1, upgradeCost: null, stage: 2, theme: 'organico', lootWeight: 1.0 },
        'fire': { id: 'fire', name: 'Core Infuocato', desc: 'Aura di fuoco che brucia i nemici al contatto infliggendo 5 DPS.', materials: { 'sand_fragment': 3, 'fire_fragment': 1 }, effect: { type: 'fire', damage: 5 }, maxLevel: 1, upgradeCost: null, stage: 3, theme: 'infuocato', lootWeight: 1.0 },
        'volcanic': { id: 'volcanic', name: 'Core Vulcanico', desc: 'Eruzioni periodiche che respingono i nemici e infliggono 8 danno.', materials: { 'obsidian_fragment': 2, 'magma_fragment': 2 }, effect: { type: 'volcanic', damage: 8, knockback: 25, cooldown: 4000 }, maxLevel: 1, upgradeCost: null, stage: 3, theme: 'infuocato', lootWeight: 0.8 },
        'frost': { id: 'frost', name: 'Core Glaciale', desc: 'Aura di ghiaccio che rallenta i nemici del 20% e infligge 4 DPS.', materials: { 'ice_fragment': 3, 'frost_fragment': 1 }, effect: { type: 'frost', slow: 0.2, damage: 4 }, maxLevel: 1, upgradeCost: null, stage: 4, theme: 'glaciale', lootWeight: 0.7 },
        'crystal': { id: 'crystal', name: 'Core di Cristallo', desc: 'Barriera di cristallo che riflette il 40% dei proiettili.', materials: { 'crystal_fragment': 2, 'energy_fragment': 2 }, effect: { type: 'crystal', reflect: 0.4, amplify: 1.5 }, maxLevel: 1, upgradeCost: null, stage: 4, theme: 'glaciale', lootWeight: 0.6 },
        'void': { id: 'void', name: 'Core del Vuoto', desc: 'Vortice viola che teletrasporta quando salute < 30%.', materials: { 'void_fragment': 1, 'cosmic_fragment': 1 }, effect: { type: 'void_teleport', threshold: 0.3, cooldown: 10000 }, maxLevel: 1, upgradeCost: null, stage: 5, theme: 'cosmico', lootWeight: 0.5 },
        'stellar': { id: 'stellar', name: 'Core Stellare', desc: 'Aura stellare che aumenta tutti i danni del 15% e rigenera 1 HP ogni 3s.', materials: { 'star_fragment': 1, 'nebula_fragment': 1 }, effect: { type: 'stellar', damage: 0.15, regen: 1, interval: 3000 }, maxLevel: 1, upgradeCost: null, stage: 5, theme: 'cosmico', lootWeight: 0.25 },
        'storm': { id: 'storm', name: 'Core di Tempesta', desc: 'Fulmini periodici che colpiscono i nemici nel raggio infliggendo 12 danno.', materials: { 'energy_fragment': 2, 'frost_fragment': 1 }, effect: { type: 'storm', damage: 12, radius: 180, cooldown: 3500 }, maxLevel: 1, upgradeCost: null, stage: 4, theme: 'glaciale', lootWeight: 0.5 },
        'blood': { id: 'blood', name: 'Core di Sangue', desc: 'Rubavita al contatto: recupera 8% del danno inflitto ai nemici.', materials: { 'poison_fragment': 2, 'void_fragment': 1 }, effect: { type: 'lifesteal', percent: 0.08 }, maxLevel: 1, upgradeCost: null, stage: 2, theme: 'organico', lootWeight: 0.8 },
        'gravity': { id: 'gravity', name: 'Core di Gravità', desc: 'Attira e rallenta i nemici nel raggio del 25%.', materials: { 'cosmic_fragment': 2, 'void_fragment': 1 }, effect: { type: 'gravity', slow: 0.25, pullStrength: 0.03, radius: 120 }, maxLevel: 1, upgradeCost: null, stage: 5, theme: 'cosmico', lootWeight: 0.3 },
        'arcane': { id: 'arcane', name: 'Core Arcano', desc: 'Aumenta tutti i danni magici del 18%.', materials: { 'star_fragment': 1, 'energy_fragment': 2 }, effect: { type: 'arcane', damagePercent: 0.18 }, maxLevel: 1, upgradeCost: null, stage: 5, theme: 'cosmico', lootWeight: 0.25 }
    },
    weapons: {
        'iron_spikes': { id: 'iron_spikes', name: 'Spine di Ferro', desc: '4 spine metalliche che danneggiano i nemici per +10 danno al contatto.', materials: { 'iron_fragment': 3, 'stone_fragment': 2 }, effect: { type: 'spikes', damage: 10, radius: 30, count: 4 }, maxLevel: 3, upgradeCost: { 'iron_fragment': 2, 'stone_fragment': 1 }, stage: 1, theme: 'metallico', lootWeight: 1.5 },
        'steel_barrier': { id: 'steel_barrier', name: "Barriera d'Acciaio", desc: 'Barriera metallica che blocca il 50% dei proiettili.', materials: { 'steel_fragment': 2, 'metal_fragment': 2 }, effect: { type: 'barrier', blockChance: 0.5, damage: 6 }, maxLevel: 3, upgradeCost: { 'steel_fragment': 1, 'metal_fragment': 1 }, stage: 1, theme: 'metallico', lootWeight: 1.3 },
        'poison_vines': { id: 'poison_vines', name: 'Viti Velenose', desc: 'Viti animate che avvelenano i nemici infliggendo 3 DPS per 4s.', materials: { 'vine_fragment': 3, 'poison_fragment': 1 }, effect: { type: 'poison_vines', damage: 3, duration: 4000, radius: 35 }, maxLevel: 3, upgradeCost: { 'vine_fragment': 2, 'poison_fragment': 1 }, stage: 2, theme: 'organico', lootWeight: 1.1 },
        'shadow_cloak': { id: 'shadow_cloak', name: "Mantello d'Ombra", desc: 'Mantello che riduce la visibilità ai nemici del 40%.', materials: { 'shadow_fragment': 2, 'wood_fragment': 2 }, effect: { type: 'shadow_cloak', stealth: 0.4, speed: 0.08 }, maxLevel: 3, upgradeCost: { 'shadow_fragment': 1, 'wood_fragment': 1 }, stage: 2, theme: 'organico', lootWeight: 1.0 },
        'fire_ring': { id: 'fire_ring', name: 'Anello di Fuoco', desc: 'Anello di fiamme che brucia i nemici infliggendo 6 DPS.', materials: { 'fire_fragment': 2, 'sand_fragment': 2 }, effect: { type: 'fire_ring', damage: 6, radius: 40 }, maxLevel: 3, upgradeCost: { 'fire_fragment': 1, 'sand_fragment': 1 }, stage: 3, theme: 'infuocato', lootWeight: 0.9 },
        'obsidian_blade': { id: 'obsidian_blade', name: 'Lama di Ossidiana', desc: '2 lame di ossidiana che tagliano i nemici per +15 danno.', materials: { 'obsidian_fragment': 3, 'magma_fragment': 1 }, effect: { type: 'obsidian_blade', damage: 15, burn: 3, count: 2 }, maxLevel: 3, upgradeCost: { 'obsidian_fragment': 2, 'magma_fragment': 1 }, stage: 3, theme: 'infuocato', lootWeight: 0.8 },
        'ice_shards': { id: 'ice_shards', name: 'Schegge di Ghiaccio', desc: '5 schegge di ghiaccio che rallentano i nemici del 25%.', materials: { 'ice_fragment': 3, 'crystal_fragment': 2 }, effect: { type: 'ice_shards', damage: 8, slow: 0.25, count: 5 }, maxLevel: 3, upgradeCost: { 'ice_fragment': 2, 'crystal_fragment': 1 }, stage: 4, theme: 'glaciale', lootWeight: 0.7 },
        'frost_field': { id: 'frost_field', name: 'Campo di Brina', desc: 'Campo di brina che rallenta i nemici del 30% e infligge 5 DPS.', materials: { 'frost_fragment': 2, 'energy_fragment': 2 }, effect: { type: 'frost_field', damage: 5, slow: 0.3, radius: 45 }, maxLevel: 3, upgradeCost: { 'frost_fragment': 1, 'energy_fragment': 1 }, stage: 4, theme: 'glaciale', lootWeight: 0.6 },
        'void_blade': { id: 'void_blade', name: 'Lama del Vuoto', desc: '3 lame del vuoto che tagliano i nemici per +18 danno.', materials: { 'void_fragment': 2, 'cosmic_fragment': 1 }, effect: { type: 'void_blade', damage: 18, slow: 0.25, duration: 4000, count: 3 }, maxLevel: 3, upgradeCost: { 'void_fragment': 1, 'cosmic_fragment': 1 }, stage: 5, theme: 'cosmico', lootWeight: 0.35 },
        'stellar_pulse': { id: 'stellar_pulse', name: 'Impulso Stellare', desc: 'Impulso cosmico che respinge i nemici infliggendo +20 danno.', materials: { 'star_fragment': 1, 'nebula_fragment': 1 }, effect: { type: 'stellar_pulse', damage: 20, knockback: 40, cooldown: 4000 }, maxLevel: 3, upgradeCost: { 'star_fragment': 1, 'nebula_fragment': 1 }, stage: 5, theme: 'cosmico', lootWeight: 0.25 },
        'arcane_lightning': { id: 'arcane_lightning', name: 'Fulmine Arcano', desc: 'Proiettile arcano che rimbalza tra i nemici infliggendo 14 danno.', materials: { 'energy_fragment': 2, 'cosmic_fragment': 1 }, effect: { type: 'arcane_lightning', damage: 14, bounces: 4, radius: 50 }, maxLevel: 3, upgradeCost: { 'energy_fragment': 1, 'cosmic_fragment': 1 }, stage: 4, theme: 'glaciale', lootWeight: 0.4 },
        'orbital_blades': { id: 'orbital_blades', name: 'Lame Orbitali', desc: '4 lame che orbitano intorno infliggendo 11 danno al contatto.', materials: { 'obsidian_fragment': 2, 'metal_fragment': 2 }, effect: { type: 'orbital_blades', damage: 11, count: 4, radius: 35 }, maxLevel: 3, upgradeCost: { 'obsidian_fragment': 1, 'metal_fragment': 1 }, stage: 3, theme: 'infuocato', lootWeight: 0.7 },
        'thorn_shield': { id: 'thorn_shield', name: 'Scudo di Spine', desc: 'Danno al contatto +20% riflessione proiettili.', materials: { 'iron_fragment': 3, 'vine_fragment': 2 }, effect: { type: 'thorn_shield', damage: 12, reflectPercent: 0.2, radius: 28 }, maxLevel: 3, upgradeCost: { 'iron_fragment': 2, 'vine_fragment': 1 }, stage: 1, theme: 'metallico', lootWeight: 1.2 },
        'corrosive_mist': { id: 'corrosive_mist', name: 'Nebbia Corrosiva', desc: 'Area DoT che avvelena i nemici per 7 DPS.', materials: { 'poison_fragment': 3, 'sand_fragment': 2 }, effect: { type: 'corrosive_mist', damage: 7, radius: 55, duration: 3000 }, maxLevel: 3, upgradeCost: { 'poison_fragment': 1, 'sand_fragment': 1 }, stage: 2, theme: 'organico', lootWeight: 0.9 }
    },
    fusions: [
        { id: 'fireball_lightning', primary: 'fireball', secondary: 'lightning', name: 'Fulmine Infuocato', desc: 'Fireball + Lightning: +40% danno fuoco, +10 burn.', bonus: { damage: 0.4, burnDamage: 10 } },
        { id: 'frostbolt_shield', primary: 'frostbolt', secondary: 'shield', name: 'Barriera Glaciale', desc: 'Frostbolt + Shield: Aura gelo +50% DPS e +20% slow.', bonus: { auraDps: 5, auraSlow: 0.2 } },
        { id: 'shotgun_heal', primary: 'shotgun', secondary: 'heal', name: 'Raffica Vitale', desc: 'Shotgun + Heal: +3 proiettili, Heal integrato.', bonus: { count: 3 } },
        { id: 'shockwave_fireball', primary: 'shockwave', secondary: 'fireball', name: 'Nova Infuocata', desc: "Onda d'urto che incendia. +50% knockback, burn 8 DPS.", bonus: { knockback: 0.5, burnDamage: 8 } },
        { id: 'lightning_frostbolt', primary: 'lightning', secondary: 'frostbolt', name: 'Tempesta Artica', desc: 'Fulmine che congela. +60% slow, chain +2.', bonus: { slow: 0.6, chains: 2 } },
        { id: 'shotgun_shockwave', primary: 'shotgun', secondary: 'shockwave', name: 'Raffica Sismica', desc: 'Proiettili che respingono in area. +30% area.', bonus: { area: 0.3 } },
        { id: 'heal_frostbolt', primary: 'heal', secondary: 'frostbolt', name: 'Rigenerazione Glaciale', desc: 'Cura che rallenta nemici. Heal +40%, area slow.', bonus: { healAmount: 0.4, auraSlow: 0.15 } },
        { id: 'shield_fireball', primary: 'shield', secondary: 'fireball', name: 'Scudo Infuocato', desc: 'Scudo che riflette con fuoco. Reflect +100% danno.', bonus: { reflectDamage: 1.0 } },
        { id: 'lightning_shotgun', primary: 'lightning', secondary: 'shotgun', name: 'Tempesta di Schegge', desc: 'Rosa di fulmini. +4 proiettili chain.', bonus: { chains: 4 } },
        // Advanced Fusions
        { id: 'tri_elemental', primary: 'fireball', secondary: 'frostbolt', tertiary: 'lightning', name: 'Triade Elementale', desc: 'Fuoco + Gelo + Fulmine MASSIMI: Il caos puro. Danni massicci e status.', bonus: { damage: 1.0, burnDamage: 25, auraDps: 15, auraSlow: 0.3, chains: 5 }, advanced: true },
        { id: 'radiant_aegis', primary: 'shield', secondary: 'heal', requiredPassive: 'armor', name: 'Egida Radiante', desc: 'Scudo + Cura + Armatura MAX: Invulnerabilità e guarigione passiva.', bonus: { reflectDamage: 2.0, healAmount: 1.0 }, advanced: true },
        { id: 'cataclysm', primary: 'shockwave', secondary: 'shotgun', tertiary: 'lightning', name: 'Cataclisma', desc: 'Nova + Fucile + Fulmine MASSIMI: Distruzione a schermo intero.', bonus: { damage: 1.5, area: 1.0, knockback: 1.0, count: 6 }, advanced: true },
        // New Cosmic Fusions
        { id: 'black_hole', primary: 'singularity', secondary: 'cyclone', name: 'Buco Nero', desc: 'Attrazione massiccia e danni periodici enormi.', bonus: { damage: 2.0, pullForce: 5, radius: 100 } },
        { id: 'spectral_veil', primary: 'cloaking', secondary: 'frostbolt', name: 'Velo Spettrale', desc: 'Invisibilità che rilascia dardi di ghiaccio durante il movimento.', bonus: { penetration: 5, damage: 0.5 } },
        { id: 'stellar_rain', primary: 'fireball', secondary: 'singularity', name: 'Pioggia Stellare', desc: 'Le fireball vengono attratte verso la Singularity creando mini-meteore.', bonus: { count: 4, damage: 0.3 } },
        { id: 'paradox', primary: 'armageddon', secondary: 'cloaking', name: 'Paradox', desc: 'L\'Armageddon ferma il tempo per 10 secondi invece di fare danni.', bonus: { timeStop: 10000 } }
    ]
};
